In [14]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

In [17]:
df=pd.read_csv("email.csv")
df

                                                   text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5728 rows x 2 columns]

In [18]:
df.groupby('spam')
df.head()

                                                text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [20]:
x_train,x_test,y_train,y_test=train_test_split(df.text,df.spam,test_size=0.20)

In [21]:
x_train

2534    Subject: ppi index short - term models  hi mar...
3132    Subject: lsu visit ( resume )  mr . kaminski ,...
1326    Subject: all graphics software available , che...
5152    Subject: re : livelink  moyez ,  we are very a...
1890    Subject: rice program in financial engineering...
                              ...
2627    Subject: continue enjoying iijournals - - rene...
1813    Subject: re : good morning  john ,  i shall se...
1579    Subject: 1 candidate and 2 interns  hi vince a...
3449    Subject: re : bryan seyfried visiting houston ...
2571    Subject: re : greetings  hi , mr . kaminski : ...
Name: text, Length: 4582, dtype: object

In [22]:
y_train

2534    0
3132    0
1326    1
5152    0
1890    0
       ..
2627    0
1813    0
1579    0
3449    0
2571    0
Name: spam, Length: 4582, dtype: int64

In [24]:
v=CountVectorizer()
x_train_count=v.fit_transform(x_train.values)
x_train_count.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [27]:
model=MultinomialNB()
model.fit(x_train_count,y_train)

MultinomialNB()

In [29]:
email=['hey vivek can we go to watch a football match tommorow','do not have money,exclusive offer ust for you , dont miss this reward!!']
email_count=v.transform(email)

In [30]:
model.predict(email_count)

array([1, 1], dtype=int64)

In [32]:
x_test_count=v.transform(x_test)
model.score(x_test_count,y_test)

0.9912739965095986